[package]
name = "allocators"
version = "0.1.0"
authors = ["lsongzhi <lsongzhi@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = { version = "0.9", default-features = false, features = ["mutex", "spin_mutex"] }
smallvec = "1.6"
cache-padded = "1.1"